spring:
  datasource:
    url: jdbc:mysql://106.14.43.178:3306/sell?characterEncoding=utf-8&useSSL=false
    username: xieyunhai
    password: Xiao.Xi.45
    driver-class-name: com.mysql.jdbc.Driver
  # 配置 session 存储
  session:
    store-type: none
# 配置默认不启用安全认证
security:
  basic:
    enabled: true
server:
  port: 8900

qipei:
  security:
    code:
      image:
        length: 6
        url: /user/*
#    browser:
#      loginPage: /login-qipei.html

