spring:
  datasource:
    druid:
      read:
        driver-class-name: com.mysql.jdbc.Driver
        username: xieyunhai
        password: Xiao.Xi.45
        url: jdbc:mysql://106.14.43.178:3306/dianping?characterEncoding=utf-8&useSSL=false
      write:
        driver-class-name: com.mysql.jdbc.Driver
        username: xieyunhai
        password: Xiao.Xi.45
        url: jdbc:mysql://106.14.43.178:3306/blog?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        enable_lazy_load_no_trans: true